### ISSUE TITLE
Public API Key

### ISSUE THREAD

**Issue by AnthonyRHoward** [snelly1998/react-weather-app-repo#1]
Hi! 

You should setup an .env file that keeps track of your API Key/Secrets rather than publicly placing your keys/secrets in plain text in your App.js file. 

`function App() {
  const [isForecast, setIsForecast] = useState(0);
  const API = REDACTED. 
  const [longitude, setLongitude] = useState(0);
  const [latitude, setLatitude] = useState(0);
  navigator.geolocation.getCurrentPosition((position) => {
    setLatitude(position.coords.latitude);
    setLongitude(position.coords.longitude);
  }
  );`

**Comment by snelly1998** [comment]
Yeah probably should but I'm not too worried about it lol, haven't touched this in about a year and if anyone actually manages to stumble here and use all of my free api requests more power to them lol
